version: "3.9"

services:
  db:
    image: mysql:8
    container_name: students-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: students-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: students-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
