apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: student-api
data:
  MYSQL_DATABASE: students_db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
        - name: migrations
          configMap:
            name: migration-sql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: student-api
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
