apiVersion: v1
kind: Namespace
metadata:
  name: dependent-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: dependent-services
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.14.2
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: dependent-services
spec:
  type: ClusterIP
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
