name: CI Pipeline

on:
  push:
    paths:
      - 'src/**'
      - 'migrations/**'
  workflow_dispatch:   # manual trigger

jobs:
  build-test-lint:
    runs-on: self-hosted
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20   

      - name: Install dependencies
        run: npm install

      - name: Build API
        shell: cmd
        run: make compose-build-api
  
      - name: Run tests
        shell: cmd
        run: make test
  
      - name: Lint code
        shell: cmd
        run: make lint


  docker:
    runs-on: self-hosted
    needs: build-test-lint
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: make docker-build

      - name: Push Docker image
        run: make docker-push
