name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'migrations/**'
  workflow_dispatch:

jobs:
  build-test-lint:
    runs-on: self-hosted
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        shell: cmd
        run: |
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env

      - name: Install dependencies
        shell: cmd
        run: npm install

      - name: Build API (Docker)
        shell: cmd
        run: make compose-build-api

      - name: Run tests (inside Docker)
        shell: cmd
        run: make compose-test

      - name: Lint code (inside Docker)
        shell: cmd
        run: make compose-lint

  update-version:
    runs-on: self-hosted
    needs: build-test-lint
    permissions:
      contents: write
    outputs:
      NEW_VERSION: ${{ steps.bump.outputs.NEW_VERSION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Bump semantic version
        id: bump
        shell: cmd
        run: |
          setlocal enabledelayedexpansion
          for /f "usebackq tokens=1-3 delims=." %%a in (".version") do (
            set major=%%a
            set minor=%%b
            set /a patch=%%c+1
          )
          set newVersion=%major%.%minor%.%patch%
          echo NEW_VERSION=%newVersion%>> %GITHUB_ENV%
          echo %newVersion%> .version
          echo ::set-output name=NEW_VERSION::%newVersion%
          endlocal

      - name: Update Helm values.yaml
        shell: powershell -ExecutionPolicy Bypass
        run: |
          (Get-Content "helm/students-api/values.yaml") `
            -replace 'tag:.*', "  tag: `"$env:NEW_VERSION`"" |
          Set-Content "helm/students-api/values.yaml"


      - name: Commit and push changes
        shell: cmd
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory C:/actions-runner/_work/Students_devops/Students_devops
          git add .version helm/students-api/values.yaml
          git commit -m "Bump version to %NEW_VERSION%" || echo No changes to commit
          git push origin main


  docker:
    runs-on: self-hosted
    needs: update-version
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: ${{ needs.update-version.outputs.NEW_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        shell: cmd
        run: |
          set DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password %DOCKER_PASSWORD%

      - name: Build Docker image
        shell: cmd
        run: |
          docker build -t %DOCKER_USERNAME%/students-api:%IMAGE_TAG% .

      - name: Push Docker image
        shell: cmd
        run: |
          docker push %DOCKER_USERNAME%/students-api:%IMAGE_TAG%
